use sakila
 
 -- (5)  Determine the total revenue generated by each store.

   select* from payment
   select* from staff
   select* from store
   
select staff.store_id,sum(amount)
from payment join staff
on payment.staff_id=staff.staff_id join store 
on staff.store_id=store.store_id group by store_id 